// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISj52a1mYiF1x1lt5qehHTzj3QsJh2dw',
    appId: '1:601205290418:web:02033f0ec331b3d195a0ab',
    messagingSenderId: '601205290418',
    projectId: 'yoga-mat-1c627',
    authDomain: 'yoga-mat-1c627.firebaseapp.com',
    storageBucket: 'yoga-mat-1c627.firebasestorage.app',
    measurementId: 'G-EEGW7SQ55M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDqvw4Aw7V1kgtTn9v0jV29k_JNjU1WA',
    appId: '1:601205290418:android:c2acb5534daa01a995a0ab',
    messagingSenderId: '601205290418',
    projectId: 'yoga-mat-1c627',
    storageBucket: 'yoga-mat-1c627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA7gPsqxKpeXYwDo-_-yN0dCaUZUTBMOo',
    appId: '1:601205290418:ios:50951427823f467795a0ab',
    messagingSenderId: '601205290418',
    projectId: 'yoga-mat-1c627',
    storageBucket: 'yoga-mat-1c627.firebasestorage.app',
    iosBundleId: 'com.example.yogaMatAss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA7gPsqxKpeXYwDo-_-yN0dCaUZUTBMOo',
    appId: '1:601205290418:ios:50951427823f467795a0ab',
    messagingSenderId: '601205290418',
    projectId: 'yoga-mat-1c627',
    storageBucket: 'yoga-mat-1c627.firebasestorage.app',
    iosBundleId: 'com.example.yogaMatAss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISj52a1mYiF1x1lt5qehHTzj3QsJh2dw',
    appId: '1:601205290418:web:7489ad2eaafeb41e95a0ab',
    messagingSenderId: '601205290418',
    projectId: 'yoga-mat-1c627',
    authDomain: 'yoga-mat-1c627.firebaseapp.com',
    storageBucket: 'yoga-mat-1c627.firebasestorage.app',
    measurementId: 'G-ZXDV3Z8N0B',
  );
}
